### ISSUE TITLE
Paste in the "messages" "log" "keyboard" buffers causes a crash

### ISSUE THREAD

**Issue by clearfeld** [4coder-editor/4coder#164] opened 2020-01-28 02:44 UTC
If you hit paste while inside the following buffers messages, log, and keyboard, 4coder will instantly crash.

Reproducible on a clean 4.1.2

**Comment by 4coder-editor** [comment] 2020-01-30 04:21
Caused by a null pointer deference, after querying for an attachment on a zero buffer id. Fixed in 4.1.3.

**Closed by 4coder-editor** 2020-01-30 04:21 UTC
