### ISSUE TITLE
[Performance issue] Line_number_margins affects rendering performance

### ISSUE THREAD

**Issue by exanimusfan** [4coder-editor/4coder#142] opened 2020-01-10 14:35 UTC
Opening a huge file (35 mb and 670000 loc) has very good performance between frames but when line_number_margins are turned on,  the performance becomes very poor, it takes  2-5 seconds between frames just to move the cursor up and down.

**Comment by exanimusfan** [comment] 2020-01-11 17:19
This might be harder to fix than I thought. I tried the same test (different file but still huge 868000 loc) on my Intel i7-8850H with an Nvidia Quadro P1000 and there is virtually no difference between line number margins on or off. The first test where the wierd rendering performance was observed was on an Ryzen 1700 with an Nvidia 1070ti. I have no clue what's causing it.

**Comment by 4coder-editor** [comment] 2020-02-06 05:43
So far I haven't been able to figure out exactly what this is about. Since it isn't consistent I would think it has to be a graphics performance problem, so the obvious things I can think of without reproducing it don't make a lot of sense.  If you or anyone else can gather more information it might help.

**Comment by 4coder-editor** [comment] 2020-05-01 13:32
I've finally found a very likely culprit for this problem. It appears that the line number rendering routine was iterating to the end of the file no matter what lines were actually in view. Should be fixed in 4.1.5.

**Closed by 4coder-editor** 2020-05-01 13:32 UTC
Labels: bug-cant-reproduce
