### ISSUE TITLE
"toggle_virtual_whitespace" command doesn't work if "enable_virtual_whitespace = false;" in config.4coder

### ISSUE THREAD

**Issue by tntmonty** [4coder-editor/4coder#168] opened 2020-02-03 11:22 UTC
In 4.1.2, if your config.4coder has "enable_virtual_whitespace = false;", then the "toggle_virtual_whitespace" doesn't work. It toggles the setting, but the buffer isn't updated by the virtual whitespace code.

I think it's because the command doesn't set the layout for the buffers, but I've not looked at this stuff that much yet.

Also, the CUSTOM_DOC for the command says it's for the current buffer, but it appears to try it on all buffers.

**Comment by 4coder-editor** [comment] 2020-02-07 21:55
As you suggested, the cause of this issue is that the buffer's layout function was set to a generic layout when it was first setup and toggle command doesn't change the layout. Since the virtual whitespace layout function checks the enable variable and falls back to the generic layout when it is set to false, this was fixed simply by setting all code buffers to use the virtual whitespace layout function. Fixed in 4.1.4.

**Closed by 4coder-editor** 2020-02-07 21:55 UTC
