### ISSUE TITLE
Is this still a bug?

### ISSUE THREAD

**Issue by boagz57** [4coder-editor/4coder#203] opened 2020-03-15 15:54 UTC
I know there was a bug in earlier versions of 4coder with binding modifiers to commands (I think the order of modifiers was causing some unintended issues or something) which meant I had to do something like this in my custom mapping file:

```
MappingScope();
SelectMapping(mapping);

SelectMap(global_id);
BindCore(jason_default_startup, CoreCode_Startup);
BindCore(default_try_exit, CoreCode_TryExit);
Bind(interactive_open_or_new, KeyCode_Control, KeyCode_O); //This gets overridden below
..........

SelectMap(file_id);
ParentMap(global_id);
BindTextInput(write_text_input);
.........

SelectMap(code_id);
ParentMap(file_id);
BindTextInput(write_text_and_auto_indent);
Bind(jason_insert_newline_below, KeyCode_O); //This Binding overwrites the Control+O for interactive_open_new command

Bind(interactive_open_or_new, KeyCode_Control, KeyCode_O); //Meaning I have to paste this again here
```

In the most recent version (4.1.4) one of the changes says:

"Bindings use exact matches for modifiers, instead of most recent sub-set matches"

I thought this would fix the above issue but it has not. Is this still a bug or am I just not using my custom mappings correctly?

**Comment by 4coder-editor** [comment] 2020-05-01 13:38
This is sort of still a bug yes. It will be fixed in 4.1.5.

What happened here is a confusion caused by inheritance. 4.1.4 did fix the fact that exact matches were chosen before loose matches, but only for the current map level, exact matches in inherited maps still weren't chosen first. This is fixed in 4.1.5.

**Closed by 4coder-editor** 2020-05-01 13:38 UTC
Labels: bug
