### ISSUE TITLE
Weird indentation after a combination of a C #define, \, and square brackets

### ISSUE THREAD

**Issue by xdnicoco** [4coder-editor/4coder#196] opened 2020-03-11 13:32 UTC
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
Paste the following into an empty c file and call auto_indent_whole_file.
```c
#define SOME_DEFINE \
some_array[some_value##some_other_value]
    
int main() {
    return 0;
}
```
**Description of the Result**
The auto indentation seems to indent everything to the opening square bracket.
![image](https://user-images.githubusercontent.com/5497895/76421978-2d604f80-63ad-11ea-9a95-6f160dcf3546.png)

**Additional notes**

**System**
OS: *Windows 10*
Graphics Driver (for graphics bugs): *Driver*

**Comment by 4coder-editor** [comment] 2020-05-02 03:41
This was caused by a bug in the lexer that would think "some_array[some_value" was not actually in a preprocessor body, because the backslash was followed by a carriage return, and so the preprocessor body state got lost. Fixed in 4.1.5.

**Closed by 4coder-editor** 2020-05-02 03:41 UTC
Labels: bug
