### ISSUE TITLE
file open freeze on mac

### ISSUE THREAD

**Issue by simonwashere** [4coder-editor/4coder#214] opened 2020-04-10 10:54 UTC
Version: 4.1.4

**Repro Steps (Including a snippet of any potentially related customization code)**
Opening files in different folders always makes 4coder freeze on my mac, that is I can open the first file fine and open other files in the same folder but when I try to open a file in a different folder from the first file opened the app just hangs and does nothing. No customisations, this is with the version downloaded from itch.io

**Description of the Result**
App freeze, need to kill it and restart.

**System**
Mac mini (2018)
macOS 10.15.4 (19E287)

**Comment by athomasoriginal** [comment] 2020-04-16 00:40
I am experiencing a similar issue.  I'm not sure if it's the same, but I will log here because the effect is the same.

## Versions

- **OS** - macos catalina - 10.15.3
- **4Coder Version** - 4.1.4
- **Customalization Layer** - None

 ## Steps to Reproduce

- Run 4coder via `./4ed`
- Open the command lister `command + o`
- Select any 4coder `.cpp` file
- Open the command lister `command + o`
- Attempt Open another 4coder `.cpp` file via `command + 0`

**Comment by simonwashere** [comment] 2020-04-16 06:45
I have seen the freeze from typing /* as well, it doesn't happen in every file for me, although it does seem to consistently happen in certain files/positions. I guess it is confusing the code parser depending on what the actual code is.

I always found the early versions of 4coder very stable and usable on windows, now I have switched to this latest version on mac it keeps crashing/freezing and losing my edits which is a bit annoying.

**Comment by Leon280698** [comment] 2020-04-16 09:10
I tried to debug this. Didn't have a lot of time but maybe this can still be helpful.
All I did was to open 4coder and do `cmd->new -> "test.cpp" -> return` and it freezes.
It seems to be stuck in `async_task_wait__inner`. Here's the call stack:
```
__psynch_cvwait (@__psynch_cvwait:6)
_pthread_cond_wait (@_pthread_cond_wait:191)
async_task_wait__inner(Application_Links*, Async_System*, unsigned long long) (/Applications/4coder.app/Contents/MacOS/custom/4coder_async_tasks.cpp:198)
async_task_wait(Application_Links*, Async_System*, unsigned long long) (/Applications/4coder.app/Contents/MacOS/custom/4coder_async_tasks.cpp:207)
get_token_array_from_buffer(Application_Links*, int) (/Applications/4coder.app/Contents/MacOS/custom/4coder_helper.cpp:42)
default_render_buffer(Application_Links*, int, unsigned int, int, unsigned int, Rect_f32) (/Applications/4coder.app/Contents/MacOS/custom/4coder_default_hooks.cpp:297)
default_render_caller(Application_Links*, Frame_Info, int) (/Applications/4coder.app/Contents/MacOS/custom/4coder_default_hooks.cpp:471)
app_step(Thread_Context*, Render_Target*, void*, Application_Step_Input*) (@app_step(Thread_Context*, Render_Target*, void*, Application_Step_Input*):3094)
-[FCoder_View updateLayer] (@-[FCoder_View updateLayer]:140)
_NSViewUpdateLayer (@_NSViewUpdateLayer:29)
-[_NSViewBackingLayer display] (@-[_NSViewBackingLayer display]:113)
CA::Layer::display_if_needed(CA::Transaction*) (@CA::Layer::display_if_needed(CA::Transaction*):175)
CA::Context::commit_transaction(CA::Transaction*, double) (@CA::Context::commit_transaction(CA::Transaction*, double):77)
CA::Transaction::commit() (@CA::Transaction::commit():172)
__62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke (@__62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke:65)
___NSRunLoopObserverCreateWithHandler_block_invoke (@___NSRunLoopObserverCreateWithHandler_block_invoke:18)
__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ (@__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__:12)
__CFRunLoopDoObservers (@__CFRunLoopDoObservers:123)
__CFRunLoopRun (@__CFRunLoopRun:191)
CFRunLoopRunSpecific (@CFRunLoopRunSpecific:122)
RunCurrentEventLoopInMode (@RunCurrentEventLoopInMode:81)
ReceiveNextEventCommon (@ReceiveNextEventCommon:145)
_BlockUntilNextEventMatchingListInModeWithFilter (@_BlockUntilNextEventMatchingListInModeWithFilter:25)
_DPSNextEvent (@_DPSNextEvent:166)
-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] (@-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]:260)
-[NSApplication run] (@-[NSApplication run]:150)
main (@main:1912)
start (@start:4)
```

**Comment by simonwashere** [comment] 2020-04-19 10:54
Actually after further investigation I think the bug is simply that you cannot have more than one file open with the automatic code indentation active. It can open multiple text files but only one that is treated as code.

**Comment by simonwashere** [comment] 2020-04-19 10:55
Is anyone actually reading these bug reports anyway?

**Comment by baines** [comment] 2020-04-20 17:11
I think it is an inconsistency in `system_acquire_global_frame_mutex` on Mac compared to Windows/Linux. I'll let Allen know.

**Comment by 4coder-editor** [comment] 2020-05-01 12:30
@simonwashere I am reading them, eventually, the whole reason I opt for an issues list is so that if I take a break I don't lose track of reported issues that are a month old.

The issue was indeed in `system_acquire_global_frame_mutex` and will be fixed in the next build.

**Closed by 4coder-editor** 2020-05-01 12:30 UTC
Labels: bug
