### ISSUE TITLE
Crashing when opening with file

### ISSUE THREAD

**Issue by GoldbergJarrett** [4coder-editor/4coder#31] opened 2019-02-09 08:54 UTC
When using bash, I made an alias to open my 4ed.exe and that works perfectly. However when I try to launch 4coder with a file it will display the correct file however when I try to manipulate the file in anyway 4coder crashes.

**Comment by krouzu** [comment] 2019-02-09 16:46
I too have an issue like this, but a bit different. When I make a new file and it is empty, after typing a few characters it 4coder seems to crash. However, if I make a new file with 4coder and then add text in another editor and reload the file it seems to work fine.

**Comment by 4coder-editor** [comment] 2019-02-13 23:13
I have fixed a few bugs that occur when editing a newly opened file for the first time, and I reorganized the startup code a little bit because it was a bit weird.  I could not reproduce the bug unfortunately, so when the next build comes out let me know if it l looks the same or better.

**Comment by osor-io** [comment] 2019-04-01 08:55
Thought this would be relevant to write here 😄 

Since you've mentioned that you've been changing that code maybe this has been addressed already. But a way I can get a consistent crash is by trying to create a file that Windows won't let you create, for example, trying to create a file named "aux". If I just use Ctrl+O and type "aux" to create a new file with that name, windows would normally show you a popup saying that that name is invalid (bad legacy reasons...) but 4coder just closes for me.

Cheers!

**Comment by 4coder-editor** [comment] 2020-05-01 21:52
This is fixed in 4.1.0 and later.

**Closed by 4coder-editor** 2020-05-01 21:52 UTC
Labels: bug, bug-possibly-fixed
