### ISSUE TITLE
Segementation fault when loading project on linux

### ISSUE THREAD

**Issue by Pilzschaf** [4coder-editor/4coder#238] opened 2020-05-09 21:16 UTC
Version: 4.1.5

**Repro Steps (Including a snippet of any potentially related customization code)**
Start 4coder on linux and try to load a project in the current working directory (load_project command). 

**Description of the Result**
4coder crashes with a segmentation fault.

**Additional notes**
I have ran 4coder through gdb resulting in the following error:
system_get_file_list (arena=0x7ffff422b0f0, directory=...) at /home/allen/4ed/code/platform_linux/linux_4ed_functions.cpp:150
I have tested this in my own projects directory and in the 4coder directory trying to load the default 4coder project file. With the same result in both cases.

**System**
OS: *Linux - 64bit 4coder version*

**Comment by Pilzschaf** [comment] 2020-05-09 21:26
I have managed to pin down the bug a bit further. As soon as the directory 4coder has been started contains a nonempty subdirectory it crashes. Or in other words as soon as it has to recursively search a directory it crashes.

**Comment by 4coder-editor** [comment] 2020-05-09 22:21
This was caused by a simple failure to clear a next pointer to zero when building a linked list of file info for the directory search. Fixed in 4.1.6.

**Closed by 4coder-editor** 2020-05-09 22:21 UTC
Labels: bug
