### ISSUE TITLE
Unsaved file indicator not displayed correctly when building with /O2

### ISSUE THREAD

**Issue by Leon280698** [4coder-editor/4coder#137] opened 2020-01-04 02:31 UTC
Something seems to be wrong with the unsaved file indicator when optimizations are turned on.
It is rendered as two red bars instead of an asterisk:
![Capture](https://user-images.githubusercontent.com/11540048/71758592-2b0be180-2ea2-11ea-83b6-9b393c7f6ec6.PNG)
Nothing was modified. I simply ran buildsuper_x64.bat with the 'release' command line option which only adds the /O2 flag.

**Comment by embededhell** [comment] 2020-01-05 11:35
I can confirm this issue.
Looks like the string is pushed onto the queue with `push_fancy_string`, which adds a reference to a buffer that is declared inside block.
A simple fix for this, in `4coder_draw.cpp, draw_file_bar`,  move line 388 `u8 space[3];` up outside of the block, making it the same scope level as `draw_fancy_line`

**Comment by 4coder-editor** [comment] 2020-01-23 20:35
I see, thanks for the report and the fix, much appreciated. Fixed in 4.1.3.

**Closed by 4coder-editor** 2020-01-23 20:35 UTC
