### ISSUE TITLE
Moving view splitter to the right crashes it

### ISSUE THREAD

**Issue by nakst** [4coder-editor/4coder#106] opened 2019-12-18 19:04 UTC
See video: https://cdn.discordapp.com/attachments/447975434483662848/656933111355015188/2019-12-18_18-56-50.flv.mp4

**Comment by 4coder-editor** [comment] 2019-12-23 19:08
Strangely enough, I can't reproduce this after trying lots of different build settings combinations, including the build that I shipped. I'm going to have to track down more examples of where this fails.

**Comment by Horthrax** [comment] 2019-12-23 19:12
Crashes for me on both sides.
Running windows 10 and not sure if spec is important but i7 8700k and gtx 2080

**Comment by 4coder-editor** [comment] 2019-12-23 19:54
Okay, it was in the graphics driver, relating to negative sized scissor boxes.  Should be fixed in 4.1.1

**Closed by 4coder-editor** 2019-12-23 19:54 UTC
